
// This file has been generated by the GUI designer. Do not modify.
namespace Road111
{
	public partial class FuelList
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.CheckButton benzin_but;

		private global::Gtk.CheckButton dizel_but;

		private global::Gtk.CheckButton electro_but;

		private global::Gtk.VSeparator vseparator3;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Road111.FuelList
			this.Name = "Road111.FuelList";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Road111.FuelList.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.Name = "vseparator1";
			this.vbox2.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vseparator1]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.benzin_but = new global::Gtk.CheckButton();
			this.benzin_but.CanFocus = true;
			this.benzin_but.Name = "benzin_but";
			this.benzin_but.Label = global::Mono.Unix.Catalog.GetString("Бензин");
			this.benzin_but.DrawIndicator = true;
			this.benzin_but.UseUnderline = true;
			this.hbox1.Add(this.benzin_but);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.benzin_but]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.dizel_but = new global::Gtk.CheckButton();
			this.dizel_but.CanFocus = true;
			this.dizel_but.Name = "dizel_but";
			this.dizel_but.Label = global::Mono.Unix.Catalog.GetString("Дизель");
			this.dizel_but.DrawIndicator = true;
			this.dizel_but.UseUnderline = true;
			this.hbox1.Add(this.dizel_but);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.dizel_but]));
			w4.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.electro_but = new global::Gtk.CheckButton();
			this.electro_but.CanFocus = true;
			this.electro_but.Name = "electro_but";
			this.electro_but.Label = global::Mono.Unix.Catalog.GetString("Электричество");
			this.electro_but.DrawIndicator = true;
			this.electro_but.UseUnderline = true;
			this.hbox1.Add(this.electro_but);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.electro_but]));
			w5.Position = 2;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator();
			this.vseparator3.Name = "vseparator3";
			this.vbox2.Add(this.vseparator3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vseparator3]));
			w7.Position = 2;
			w1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w8.Position = 0;
			// Internal child Road111.FuelList.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonOk]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 300;
			this.Show();
			this.buttonCancel.Clicked += new global::System.EventHandler(this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
