
// This file has been generated by the GUI designer. Do not modify.
namespace Road111
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.Button start_stop;

		private global::Gtk.Table table1;

		private global::Gtk.Button button1;

		private global::Gtk.Button button2;

		private global::Gtk.Button button3;

		private global::Gtk.Button button4;

		private global::Gtk.Button button5;

		private global::Gtk.DrawingArea drawingarea1;

		private global::Gtk.DrawingArea drawingarea2;

		private global::Gtk.DrawingArea drawingarea3;

		private global::Gtk.DrawingArea drawingarea4;

		private global::Gtk.DrawingArea drawingarea5;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HSeparator hseparator10;

		private global::Gtk.HSeparator hseparator11;

		private global::Gtk.HSeparator hseparator12;

		private global::Gtk.HSeparator hseparator13;

		private global::Gtk.HSeparator hseparator14;

		private global::Gtk.HSeparator hseparator15;

		private global::Gtk.HSeparator hseparator16;

		private global::Gtk.HSeparator hseparator17;

		private global::Gtk.HSeparator hseparator18;

		private global::Gtk.HSeparator hseparator19;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.HSeparator hseparator20;

		private global::Gtk.HSeparator hseparator21;

		private global::Gtk.HSeparator hseparator22;

		private global::Gtk.HSeparator hseparator23;

		private global::Gtk.HSeparator hseparator24;

		private global::Gtk.HSeparator hseparator25;

		private global::Gtk.HSeparator hseparator26;

		private global::Gtk.HSeparator hseparator27;

		private global::Gtk.HSeparator hseparator28;

		private global::Gtk.HSeparator hseparator29;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.HSeparator hseparator30;

		private global::Gtk.HSeparator hseparator31;

		private global::Gtk.HSeparator hseparator32;

		private global::Gtk.HSeparator hseparator33;

		private global::Gtk.HSeparator hseparator34;

		private global::Gtk.HSeparator hseparator35;

		private global::Gtk.HSeparator hseparator4;

		private global::Gtk.HSeparator hseparator5;

		private global::Gtk.HSeparator hseparator6;

		private global::Gtk.HSeparator hseparator7;

		private global::Gtk.HSeparator hseparator8;

		private global::Gtk.HSeparator hseparator9;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Table table3;

		private global::Gtk.Label distlabel1;

		private global::Gtk.ToggleButton info_but1;

		private global::Gtk.Label label26;

		private global::Gtk.Label label31;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.Label lights9;

		private global::Gtk.CheckButton lightsbutton1;

		private global::Gtk.Label speedlabel1;

		private global::Gtk.Table table4;

		private global::Gtk.Label distlabel2;

		private global::Gtk.ToggleButton info_but2;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.Label label27;

		private global::Gtk.Label label32;

		private global::Gtk.Label lights10;

		private global::Gtk.CheckButton lightsbutton2;

		private global::Gtk.Label speedlabel2;

		private global::Gtk.Table table5;

		private global::Gtk.Label distlabel3;

		private global::Gtk.ToggleButton info_but3;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Label label16;

		private global::Gtk.Label label17;

		private global::Gtk.Label label28;

		private global::Gtk.Label label33;

		private global::Gtk.Label lights11;

		private global::Gtk.CheckButton lightsbutton3;

		private global::Gtk.Label speedlabel3;

		private global::Gtk.Table table6;

		private global::Gtk.Label distlabel4;

		private global::Gtk.ToggleButton info_but4;

		private global::Gtk.Label label18;

		private global::Gtk.Label label19;

		private global::Gtk.Label label20;

		private global::Gtk.Label label21;

		private global::Gtk.Label label29;

		private global::Gtk.Label label34;

		private global::Gtk.Label lights13;

		private global::Gtk.CheckButton lightsbutton4;

		private global::Gtk.Label speedlabel4;

		private global::Gtk.Table table7;

		private global::Gtk.Label distlabel5;

		private global::Gtk.ToggleButton info_but5;

		private global::Gtk.Label label22;

		private global::Gtk.Label label23;

		private global::Gtk.Label label24;

		private global::Gtk.Label label25;

		private global::Gtk.Label label30;

		private global::Gtk.Label label35;

		private global::Gtk.Label lights12;

		private global::Gtk.CheckButton lightsbutton5;

		private global::Gtk.Label speedlabel5;

		private global::Gtk.VBox vbox3;

		private global::Gtk.RadioButton common1;

		private global::Gtk.RadioButton railway1;

		private global::Gtk.RadioButton electrified1;

		private global::Gtk.VBox vbox4;

		private global::Gtk.RadioButton common2;

		private global::Gtk.RadioButton railway2;

		private global::Gtk.RadioButton electrified2;

		private global::Gtk.VBox vbox5;

		private global::Gtk.RadioButton common3;

		private global::Gtk.RadioButton railway3;

		private global::Gtk.RadioButton electrified3;

		private global::Gtk.VBox vbox6;

		private global::Gtk.RadioButton common4;

		private global::Gtk.RadioButton railway4;

		private global::Gtk.RadioButton electrified4;

		private global::Gtk.VBox vbox7;

		private global::Gtk.RadioButton common5;

		private global::Gtk.RadioButton railway5;

		private global::Gtk.RadioButton electrified5;

		private global::Gtk.Table table2;

		private global::Gtk.Label elTime;

		private global::Gtk.Label labelNTR;

		private global::Gtk.Label labelTelapsed;

		private global::Gtk.Label labelTmove;

		private global::Gtk.Label labelTstop;

		private global::Gtk.Label numTransport;

		private global::Gtk.Label sumMoveTime;

		private global::Gtk.Label sumStopTime;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Road111.MainWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.WidthRequest = 700;
			this.HeightRequest = 800;
			this.Name = "Road111.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Road111.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar1\'><menu><menuitem/><menuitem/><menuitem/></menu><menu/" +
					"><menu/></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add(this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.start_stop = new global::Gtk.Button();
			this.start_stop.CanFocus = true;
			this.start_stop.Name = "start_stop";
			this.start_stop.UseUnderline = true;
			this.start_stop.Label = global::Mono.Unix.Catalog.GetString("START/STOP");
			this.vbox1.Add(this.start_stop);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.start_stop]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(12)), ((uint)(5)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Add Transport");
			this.table1.Add(this.button1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.button1]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(4));
			w4.RightAttach = ((uint)(5));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Add Transport");
			this.table1.Add(this.button2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.button2]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.LeftAttach = ((uint)(4));
			w5.RightAttach = ((uint)(5));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Add Transport");
			this.table1.Add(this.button3);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.button3]));
			w6.TopAttach = ((uint)(5));
			w6.BottomAttach = ((uint)(6));
			w6.LeftAttach = ((uint)(4));
			w6.RightAttach = ((uint)(5));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button4 = new global::Gtk.Button();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Add Transport");
			this.table1.Add(this.button4);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.button4]));
			w7.TopAttach = ((uint)(7));
			w7.BottomAttach = ((uint)(8));
			w7.LeftAttach = ((uint)(4));
			w7.RightAttach = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button5 = new global::Gtk.Button();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Add Transport");
			this.table1.Add(this.button5);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.button5]));
			w8.TopAttach = ((uint)(9));
			w8.BottomAttach = ((uint)(10));
			w8.LeftAttach = ((uint)(4));
			w8.RightAttach = ((uint)(5));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea1 = new global::Gtk.DrawingArea();
			this.drawingarea1.Name = "drawingarea1";
			this.table1.Add(this.drawingarea1);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea1]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea2 = new global::Gtk.DrawingArea();
			this.drawingarea2.Name = "drawingarea2";
			this.table1.Add(this.drawingarea2);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea2]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea3 = new global::Gtk.DrawingArea();
			this.drawingarea3.Name = "drawingarea3";
			this.table1.Add(this.drawingarea3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea3]));
			w11.TopAttach = ((uint)(5));
			w11.BottomAttach = ((uint)(6));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea4 = new global::Gtk.DrawingArea();
			this.drawingarea4.Name = "drawingarea4";
			this.table1.Add(this.drawingarea4);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea4]));
			w12.TopAttach = ((uint)(7));
			w12.BottomAttach = ((uint)(8));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea5 = new global::Gtk.DrawingArea();
			this.drawingarea5.Name = "drawingarea5";
			this.table1.Add(this.drawingarea5);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea5]));
			w13.TopAttach = ((uint)(9));
			w13.BottomAttach = ((uint)(10));
			w13.LeftAttach = ((uint)(2));
			w13.RightAttach = ((uint)(3));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.table1.Add(this.hseparator1);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator1]));
			w14.LeftAttach = ((uint)(4));
			w14.RightAttach = ((uint)(5));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator10 = new global::Gtk.HSeparator();
			this.hseparator10.Name = "hseparator10";
			this.table1.Add(this.hseparator10);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator10]));
			w15.TopAttach = ((uint)(4));
			w15.BottomAttach = ((uint)(5));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator11 = new global::Gtk.HSeparator();
			this.hseparator11.Name = "hseparator11";
			this.table1.Add(this.hseparator11);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator11]));
			w16.TopAttach = ((uint)(4));
			w16.BottomAttach = ((uint)(5));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator12 = new global::Gtk.HSeparator();
			this.hseparator12.Name = "hseparator12";
			this.table1.Add(this.hseparator12);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator12]));
			w17.TopAttach = ((uint)(4));
			w17.BottomAttach = ((uint)(5));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator13 = new global::Gtk.HSeparator();
			this.hseparator13.Name = "hseparator13";
			this.table1.Add(this.hseparator13);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator13]));
			w18.TopAttach = ((uint)(6));
			w18.BottomAttach = ((uint)(7));
			w18.LeftAttach = ((uint)(4));
			w18.RightAttach = ((uint)(5));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator14 = new global::Gtk.HSeparator();
			this.hseparator14.Name = "hseparator14";
			this.table1.Add(this.hseparator14);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator14]));
			w19.TopAttach = ((uint)(6));
			w19.BottomAttach = ((uint)(7));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator15 = new global::Gtk.HSeparator();
			this.hseparator15.Name = "hseparator15";
			this.table1.Add(this.hseparator15);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator15]));
			w20.TopAttach = ((uint)(6));
			w20.BottomAttach = ((uint)(7));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator16 = new global::Gtk.HSeparator();
			this.hseparator16.Name = "hseparator16";
			this.table1.Add(this.hseparator16);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator16]));
			w21.TopAttach = ((uint)(6));
			w21.BottomAttach = ((uint)(7));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator17 = new global::Gtk.HSeparator();
			this.hseparator17.Name = "hseparator17";
			this.table1.Add(this.hseparator17);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator17]));
			w22.TopAttach = ((uint)(11));
			w22.BottomAttach = ((uint)(12));
			w22.LeftAttach = ((uint)(4));
			w22.RightAttach = ((uint)(5));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator18 = new global::Gtk.HSeparator();
			this.hseparator18.Name = "hseparator18";
			this.table1.Add(this.hseparator18);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator18]));
			w23.TopAttach = ((uint)(11));
			w23.BottomAttach = ((uint)(12));
			w23.LeftAttach = ((uint)(2));
			w23.RightAttach = ((uint)(3));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator19 = new global::Gtk.HSeparator();
			this.hseparator19.Name = "hseparator19";
			this.table1.Add(this.hseparator19);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator19]));
			w24.TopAttach = ((uint)(11));
			w24.BottomAttach = ((uint)(12));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.table1.Add(this.hseparator2);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator2]));
			w25.LeftAttach = ((uint)(2));
			w25.RightAttach = ((uint)(3));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator20 = new global::Gtk.HSeparator();
			this.hseparator20.Name = "hseparator20";
			this.table1.Add(this.hseparator20);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator20]));
			w26.TopAttach = ((uint)(11));
			w26.BottomAttach = ((uint)(12));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator21 = new global::Gtk.HSeparator();
			this.hseparator21.Name = "hseparator21";
			this.table1.Add(this.hseparator21);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator21]));
			w27.LeftAttach = ((uint)(3));
			w27.RightAttach = ((uint)(4));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator22 = new global::Gtk.HSeparator();
			this.hseparator22.Name = "hseparator22";
			this.table1.Add(this.hseparator22);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator22]));
			w28.TopAttach = ((uint)(10));
			w28.BottomAttach = ((uint)(11));
			w28.LeftAttach = ((uint)(4));
			w28.RightAttach = ((uint)(5));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator23 = new global::Gtk.HSeparator();
			this.hseparator23.Name = "hseparator23";
			this.table1.Add(this.hseparator23);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator23]));
			w29.TopAttach = ((uint)(10));
			w29.BottomAttach = ((uint)(11));
			w29.LeftAttach = ((uint)(2));
			w29.RightAttach = ((uint)(3));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator24 = new global::Gtk.HSeparator();
			this.hseparator24.Name = "hseparator24";
			this.table1.Add(this.hseparator24);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator24]));
			w30.TopAttach = ((uint)(10));
			w30.BottomAttach = ((uint)(11));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator25 = new global::Gtk.HSeparator();
			this.hseparator25.Name = "hseparator25";
			this.table1.Add(this.hseparator25);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator25]));
			w31.TopAttach = ((uint)(10));
			w31.BottomAttach = ((uint)(11));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator26 = new global::Gtk.HSeparator();
			this.hseparator26.Name = "hseparator26";
			this.table1.Add(this.hseparator26);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator26]));
			w32.TopAttach = ((uint)(8));
			w32.BottomAttach = ((uint)(9));
			w32.LeftAttach = ((uint)(4));
			w32.RightAttach = ((uint)(5));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator27 = new global::Gtk.HSeparator();
			this.hseparator27.Name = "hseparator27";
			this.table1.Add(this.hseparator27);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator27]));
			w33.TopAttach = ((uint)(8));
			w33.BottomAttach = ((uint)(9));
			w33.LeftAttach = ((uint)(2));
			w33.RightAttach = ((uint)(3));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator28 = new global::Gtk.HSeparator();
			this.hseparator28.Name = "hseparator28";
			this.table1.Add(this.hseparator28);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator28]));
			w34.TopAttach = ((uint)(8));
			w34.BottomAttach = ((uint)(9));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator29 = new global::Gtk.HSeparator();
			this.hseparator29.Name = "hseparator29";
			this.table1.Add(this.hseparator29);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator29]));
			w35.TopAttach = ((uint)(8));
			w35.BottomAttach = ((uint)(9));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.table1.Add(this.hseparator3);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator3]));
			w36.LeftAttach = ((uint)(1));
			w36.RightAttach = ((uint)(2));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator30 = new global::Gtk.HSeparator();
			this.hseparator30.Name = "hseparator30";
			this.table1.Add(this.hseparator30);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator30]));
			w37.TopAttach = ((uint)(2));
			w37.BottomAttach = ((uint)(3));
			w37.LeftAttach = ((uint)(3));
			w37.RightAttach = ((uint)(4));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator31 = new global::Gtk.HSeparator();
			this.hseparator31.Name = "hseparator31";
			this.table1.Add(this.hseparator31);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator31]));
			w38.TopAttach = ((uint)(6));
			w38.BottomAttach = ((uint)(7));
			w38.LeftAttach = ((uint)(3));
			w38.RightAttach = ((uint)(4));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator32 = new global::Gtk.HSeparator();
			this.hseparator32.Name = "hseparator32";
			this.table1.Add(this.hseparator32);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator32]));
			w39.TopAttach = ((uint)(4));
			w39.BottomAttach = ((uint)(5));
			w39.LeftAttach = ((uint)(3));
			w39.RightAttach = ((uint)(4));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator33 = new global::Gtk.HSeparator();
			this.hseparator33.Name = "hseparator33";
			this.table1.Add(this.hseparator33);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator33]));
			w40.TopAttach = ((uint)(8));
			w40.BottomAttach = ((uint)(9));
			w40.LeftAttach = ((uint)(3));
			w40.RightAttach = ((uint)(4));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator34 = new global::Gtk.HSeparator();
			this.hseparator34.Name = "hseparator34";
			this.table1.Add(this.hseparator34);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator34]));
			w41.TopAttach = ((uint)(10));
			w41.BottomAttach = ((uint)(11));
			w41.LeftAttach = ((uint)(3));
			w41.RightAttach = ((uint)(4));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator35 = new global::Gtk.HSeparator();
			this.hseparator35.Name = "hseparator35";
			this.table1.Add(this.hseparator35);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator35]));
			w42.TopAttach = ((uint)(11));
			w42.BottomAttach = ((uint)(12));
			w42.LeftAttach = ((uint)(3));
			w42.RightAttach = ((uint)(4));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator4 = new global::Gtk.HSeparator();
			this.hseparator4.Name = "hseparator4";
			this.table1.Add(this.hseparator4);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator4]));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator5 = new global::Gtk.HSeparator();
			this.hseparator5.Name = "hseparator5";
			this.table1.Add(this.hseparator5);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator5]));
			w44.TopAttach = ((uint)(2));
			w44.BottomAttach = ((uint)(3));
			w44.LeftAttach = ((uint)(4));
			w44.RightAttach = ((uint)(5));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator6 = new global::Gtk.HSeparator();
			this.hseparator6.Name = "hseparator6";
			this.table1.Add(this.hseparator6);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator6]));
			w45.TopAttach = ((uint)(2));
			w45.BottomAttach = ((uint)(3));
			w45.LeftAttach = ((uint)(2));
			w45.RightAttach = ((uint)(3));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator7 = new global::Gtk.HSeparator();
			this.hseparator7.Name = "hseparator7";
			this.table1.Add(this.hseparator7);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator7]));
			w46.TopAttach = ((uint)(2));
			w46.BottomAttach = ((uint)(3));
			w46.LeftAttach = ((uint)(1));
			w46.RightAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator8 = new global::Gtk.HSeparator();
			this.hseparator8.Name = "hseparator8";
			this.table1.Add(this.hseparator8);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator8]));
			w47.TopAttach = ((uint)(2));
			w47.BottomAttach = ((uint)(3));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator9 = new global::Gtk.HSeparator();
			this.hseparator9.Name = "hseparator9";
			this.table1.Add(this.hseparator9);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator9]));
			w48.TopAttach = ((uint)(4));
			w48.BottomAttach = ((uint)(5));
			w48.LeftAttach = ((uint)(4));
			w48.RightAttach = ((uint)(5));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("№ 1");
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w49.TopAttach = ((uint)(1));
			w49.BottomAttach = ((uint)(2));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("№ 2");
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w50.TopAttach = ((uint)(3));
			w50.BottomAttach = ((uint)(4));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("№ 3");
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w51.TopAttach = ((uint)(5));
			w51.BottomAttach = ((uint)(6));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("№ 4");
			this.table1.Add(this.label4);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
			w52.TopAttach = ((uint)(7));
			w52.BottomAttach = ((uint)(8));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(1));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("№ 5");
			this.table1.Add(this.label5);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table1[this.label5]));
			w53.TopAttach = ((uint)(9));
			w53.BottomAttach = ((uint)(10));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.table3 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.distlabel1 = new global::Gtk.Label();
			this.distlabel1.Name = "distlabel1";
			this.distlabel1.Xalign = 1F;
			this.table3.Add(this.distlabel1);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table3[this.distlabel1]));
			w54.TopAttach = ((uint)(3));
			w54.BottomAttach = ((uint)(4));
			w54.LeftAttach = ((uint)(1));
			w54.RightAttach = ((uint)(2));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.info_but1 = new global::Gtk.ToggleButton();
			this.info_but1.Sensitive = false;
			this.info_but1.CanFocus = true;
			this.info_but1.Name = "info_but1";
			this.info_but1.UseUnderline = true;
			this.info_but1.Label = global::Mono.Unix.Catalog.GetString("Свойства");
			this.table3.Add(this.info_but1);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table3[this.info_but1]));
			w55.TopAttach = ((uint)(5));
			w55.BottomAttach = ((uint)(6));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label26 = new global::Gtk.Label();
			this.label26.Name = "label26";
			this.label26.Xalign = 1F;
			this.table3.Add(this.label26);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table3[this.label26]));
			w56.TopAttach = ((uint)(1));
			w56.BottomAttach = ((uint)(2));
			w56.LeftAttach = ((uint)(1));
			w56.RightAttach = ((uint)(2));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label31 = new global::Gtk.Label();
			this.label31.Name = "label31";
			this.label31.Xalign = 1F;
			this.table3.Add(this.label31);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table3[this.label31]));
			w57.LeftAttach = ((uint)(1));
			w57.RightAttach = ((uint)(2));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Тип Транспорта:");
			this.table3.Add(this.label6);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table3[this.label6]));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Тип топлива:");
			this.table3.Add(this.label7);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table3[this.label7]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Скорость (км/ч):");
			this.table3.Add(this.label8);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table3[this.label8]));
			w60.TopAttach = ((uint)(2));
			w60.BottomAttach = ((uint)(3));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Пройдено (км):");
			this.table3.Add(this.label9);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table3[this.label9]));
			w61.TopAttach = ((uint)(3));
			w61.BottomAttach = ((uint)(4));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lights9 = new global::Gtk.Label();
			this.lights9.Name = "lights9";
			this.lights9.Xalign = 0F;
			this.lights9.LabelProp = global::Mono.Unix.Catalog.GetString("Свет");
			this.table3.Add(this.lights9);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table3[this.lights9]));
			w62.TopAttach = ((uint)(4));
			w62.BottomAttach = ((uint)(5));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lightsbutton1 = new global::Gtk.CheckButton();
			this.lightsbutton1.Sensitive = false;
			this.lightsbutton1.CanFocus = true;
			this.lightsbutton1.Name = "lightsbutton1";
			this.lightsbutton1.Label = "";
			this.lightsbutton1.DrawIndicator = true;
			this.lightsbutton1.UseUnderline = true;
			this.table3.Add(this.lightsbutton1);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table3[this.lightsbutton1]));
			w63.TopAttach = ((uint)(4));
			w63.BottomAttach = ((uint)(5));
			w63.LeftAttach = ((uint)(1));
			w63.RightAttach = ((uint)(2));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.speedlabel1 = new global::Gtk.Label();
			this.speedlabel1.Name = "speedlabel1";
			this.speedlabel1.Xalign = 1F;
			this.table3.Add(this.speedlabel1);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table3[this.speedlabel1]));
			w64.TopAttach = ((uint)(2));
			w64.BottomAttach = ((uint)(3));
			w64.LeftAttach = ((uint)(1));
			w64.RightAttach = ((uint)(2));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table1.Add(this.table3);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table1[this.table3]));
			w65.TopAttach = ((uint)(1));
			w65.BottomAttach = ((uint)(2));
			w65.LeftAttach = ((uint)(3));
			w65.RightAttach = ((uint)(4));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.table4 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.distlabel2 = new global::Gtk.Label();
			this.distlabel2.Name = "distlabel2";
			this.distlabel2.Xalign = 1F;
			this.table4.Add(this.distlabel2);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table4[this.distlabel2]));
			w66.TopAttach = ((uint)(3));
			w66.BottomAttach = ((uint)(4));
			w66.LeftAttach = ((uint)(1));
			w66.RightAttach = ((uint)(2));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.info_but2 = new global::Gtk.ToggleButton();
			this.info_but2.Sensitive = false;
			this.info_but2.CanFocus = true;
			this.info_but2.Name = "info_but2";
			this.info_but2.UseUnderline = true;
			this.info_but2.Active = true;
			this.info_but2.Label = global::Mono.Unix.Catalog.GetString("Свойства");
			this.table4.Add(this.info_but2);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table4[this.info_but2]));
			w67.TopAttach = ((uint)(5));
			w67.BottomAttach = ((uint)(6));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Тип транспорта:");
			this.table4.Add(this.label10);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table4[this.label10]));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Тип топлива:");
			this.table4.Add(this.label11);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table4[this.label11]));
			w69.TopAttach = ((uint)(1));
			w69.BottomAttach = ((uint)(2));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Скорость (км/ч):");
			this.table4.Add(this.label12);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table4[this.label12]));
			w70.TopAttach = ((uint)(2));
			w70.BottomAttach = ((uint)(3));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Пройдено (км)");
			this.table4.Add(this.label13);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table4[this.label13]));
			w71.TopAttach = ((uint)(3));
			w71.BottomAttach = ((uint)(4));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.Xalign = 1F;
			this.table4.Add(this.label27);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table4[this.label27]));
			w72.TopAttach = ((uint)(1));
			w72.BottomAttach = ((uint)(2));
			w72.LeftAttach = ((uint)(1));
			w72.RightAttach = ((uint)(2));
			w72.XOptions = ((global::Gtk.AttachOptions)(4));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label32 = new global::Gtk.Label();
			this.label32.Name = "label32";
			this.label32.Xalign = 1F;
			this.table4.Add(this.label32);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.table4[this.label32]));
			w73.LeftAttach = ((uint)(1));
			w73.RightAttach = ((uint)(2));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lights10 = new global::Gtk.Label();
			this.lights10.Name = "lights10";
			this.lights10.Xalign = 0F;
			this.lights10.LabelProp = global::Mono.Unix.Catalog.GetString("Свет");
			this.table4.Add(this.lights10);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.table4[this.lights10]));
			w74.TopAttach = ((uint)(4));
			w74.BottomAttach = ((uint)(5));
			w74.XOptions = ((global::Gtk.AttachOptions)(4));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lightsbutton2 = new global::Gtk.CheckButton();
			this.lightsbutton2.Sensitive = false;
			this.lightsbutton2.CanFocus = true;
			this.lightsbutton2.Name = "lightsbutton2";
			this.lightsbutton2.Label = "";
			this.lightsbutton2.DrawIndicator = true;
			this.lightsbutton2.UseUnderline = true;
			this.table4.Add(this.lightsbutton2);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table4[this.lightsbutton2]));
			w75.TopAttach = ((uint)(4));
			w75.BottomAttach = ((uint)(5));
			w75.LeftAttach = ((uint)(1));
			w75.RightAttach = ((uint)(2));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.speedlabel2 = new global::Gtk.Label();
			this.speedlabel2.Name = "speedlabel2";
			this.speedlabel2.Xalign = 1F;
			this.table4.Add(this.speedlabel2);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table4[this.speedlabel2]));
			w76.TopAttach = ((uint)(2));
			w76.BottomAttach = ((uint)(3));
			w76.LeftAttach = ((uint)(1));
			w76.RightAttach = ((uint)(2));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table1.Add(this.table4);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table1[this.table4]));
			w77.TopAttach = ((uint)(3));
			w77.BottomAttach = ((uint)(4));
			w77.LeftAttach = ((uint)(3));
			w77.RightAttach = ((uint)(4));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.table5 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.distlabel3 = new global::Gtk.Label();
			this.distlabel3.Name = "distlabel3";
			this.distlabel3.Xalign = 1F;
			this.table5.Add(this.distlabel3);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table5[this.distlabel3]));
			w78.TopAttach = ((uint)(3));
			w78.BottomAttach = ((uint)(4));
			w78.LeftAttach = ((uint)(1));
			w78.RightAttach = ((uint)(2));
			w78.XOptions = ((global::Gtk.AttachOptions)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.info_but3 = new global::Gtk.ToggleButton();
			this.info_but3.Sensitive = false;
			this.info_but3.CanFocus = true;
			this.info_but3.Name = "info_but3";
			this.info_but3.UseUnderline = true;
			this.info_but3.Label = global::Mono.Unix.Catalog.GetString("Свойства");
			this.table5.Add(this.info_but3);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table5[this.info_but3]));
			w79.TopAttach = ((uint)(5));
			w79.BottomAttach = ((uint)(6));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Тип транспорта:");
			this.table5.Add(this.label14);
			global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table5[this.label14]));
			w80.XOptions = ((global::Gtk.AttachOptions)(4));
			w80.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.Xalign = 0F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Тип топлива:");
			this.table5.Add(this.label15);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table5[this.label15]));
			w81.TopAttach = ((uint)(1));
			w81.BottomAttach = ((uint)(2));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.Xalign = 0F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Скорость (км/ч):");
			this.table5.Add(this.label16);
			global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.table5[this.label16]));
			w82.TopAttach = ((uint)(2));
			w82.BottomAttach = ((uint)(3));
			w82.XOptions = ((global::Gtk.AttachOptions)(4));
			w82.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.Xalign = 0F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Пройдено (км):");
			this.table5.Add(this.label17);
			global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.table5[this.label17]));
			w83.TopAttach = ((uint)(3));
			w83.BottomAttach = ((uint)(4));
			w83.XOptions = ((global::Gtk.AttachOptions)(4));
			w83.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label28 = new global::Gtk.Label();
			this.label28.Name = "label28";
			this.label28.Xalign = 1F;
			this.table5.Add(this.label28);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table5[this.label28]));
			w84.TopAttach = ((uint)(1));
			w84.BottomAttach = ((uint)(2));
			w84.LeftAttach = ((uint)(1));
			w84.RightAttach = ((uint)(2));
			w84.XOptions = ((global::Gtk.AttachOptions)(4));
			w84.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label33 = new global::Gtk.Label();
			this.label33.Name = "label33";
			this.label33.Xalign = 1F;
			this.table5.Add(this.label33);
			global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table5[this.label33]));
			w85.LeftAttach = ((uint)(1));
			w85.RightAttach = ((uint)(2));
			w85.XOptions = ((global::Gtk.AttachOptions)(4));
			w85.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.lights11 = new global::Gtk.Label();
			this.lights11.Name = "lights11";
			this.lights11.Xalign = 0F;
			this.lights11.LabelProp = global::Mono.Unix.Catalog.GetString("Свет");
			this.table5.Add(this.lights11);
			global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table5[this.lights11]));
			w86.TopAttach = ((uint)(4));
			w86.BottomAttach = ((uint)(5));
			w86.XOptions = ((global::Gtk.AttachOptions)(4));
			w86.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.lightsbutton3 = new global::Gtk.CheckButton();
			this.lightsbutton3.Sensitive = false;
			this.lightsbutton3.CanFocus = true;
			this.lightsbutton3.Name = "lightsbutton3";
			this.lightsbutton3.Label = "";
			this.lightsbutton3.DrawIndicator = true;
			this.lightsbutton3.UseUnderline = true;
			this.table5.Add(this.lightsbutton3);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.table5[this.lightsbutton3]));
			w87.TopAttach = ((uint)(4));
			w87.BottomAttach = ((uint)(5));
			w87.LeftAttach = ((uint)(1));
			w87.RightAttach = ((uint)(2));
			w87.XOptions = ((global::Gtk.AttachOptions)(4));
			w87.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.speedlabel3 = new global::Gtk.Label();
			this.speedlabel3.Name = "speedlabel3";
			this.speedlabel3.Xalign = 1F;
			this.table5.Add(this.speedlabel3);
			global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.table5[this.speedlabel3]));
			w88.TopAttach = ((uint)(2));
			w88.BottomAttach = ((uint)(3));
			w88.LeftAttach = ((uint)(1));
			w88.RightAttach = ((uint)(2));
			w88.XOptions = ((global::Gtk.AttachOptions)(4));
			w88.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table1.Add(this.table5);
			global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.table1[this.table5]));
			w89.TopAttach = ((uint)(5));
			w89.BottomAttach = ((uint)(6));
			w89.LeftAttach = ((uint)(3));
			w89.RightAttach = ((uint)(4));
			w89.XOptions = ((global::Gtk.AttachOptions)(4));
			w89.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.table6 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
			this.table6.Name = "table6";
			this.table6.RowSpacing = ((uint)(6));
			this.table6.ColumnSpacing = ((uint)(6));
			// Container child table6.Gtk.Table+TableChild
			this.distlabel4 = new global::Gtk.Label();
			this.distlabel4.Name = "distlabel4";
			this.distlabel4.Xalign = 1F;
			this.table6.Add(this.distlabel4);
			global::Gtk.Table.TableChild w90 = ((global::Gtk.Table.TableChild)(this.table6[this.distlabel4]));
			w90.TopAttach = ((uint)(3));
			w90.BottomAttach = ((uint)(4));
			w90.LeftAttach = ((uint)(1));
			w90.RightAttach = ((uint)(2));
			w90.XOptions = ((global::Gtk.AttachOptions)(4));
			w90.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.info_but4 = new global::Gtk.ToggleButton();
			this.info_but4.Sensitive = false;
			this.info_but4.CanFocus = true;
			this.info_but4.Name = "info_but4";
			this.info_but4.UseUnderline = true;
			this.info_but4.Label = global::Mono.Unix.Catalog.GetString("Свойства");
			this.table6.Add(this.info_but4);
			global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.table6[this.info_but4]));
			w91.TopAttach = ((uint)(5));
			w91.BottomAttach = ((uint)(6));
			w91.XOptions = ((global::Gtk.AttachOptions)(4));
			w91.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.Xalign = 0F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Тип транспорта:");
			this.table6.Add(this.label18);
			global::Gtk.Table.TableChild w92 = ((global::Gtk.Table.TableChild)(this.table6[this.label18]));
			w92.XOptions = ((global::Gtk.AttachOptions)(4));
			w92.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.Xalign = 0F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Тип топлива:");
			this.table6.Add(this.label19);
			global::Gtk.Table.TableChild w93 = ((global::Gtk.Table.TableChild)(this.table6[this.label19]));
			w93.TopAttach = ((uint)(1));
			w93.BottomAttach = ((uint)(2));
			w93.XOptions = ((global::Gtk.AttachOptions)(4));
			w93.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.Xalign = 0F;
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Скорость (км/ч):");
			this.table6.Add(this.label20);
			global::Gtk.Table.TableChild w94 = ((global::Gtk.Table.TableChild)(this.table6[this.label20]));
			w94.TopAttach = ((uint)(2));
			w94.BottomAttach = ((uint)(3));
			w94.XOptions = ((global::Gtk.AttachOptions)(4));
			w94.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.Xalign = 0F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Пройдено (км):");
			this.table6.Add(this.label21);
			global::Gtk.Table.TableChild w95 = ((global::Gtk.Table.TableChild)(this.table6[this.label21]));
			w95.TopAttach = ((uint)(3));
			w95.BottomAttach = ((uint)(4));
			w95.XOptions = ((global::Gtk.AttachOptions)(4));
			w95.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.Xalign = 1F;
			this.table6.Add(this.label29);
			global::Gtk.Table.TableChild w96 = ((global::Gtk.Table.TableChild)(this.table6[this.label29]));
			w96.TopAttach = ((uint)(1));
			w96.BottomAttach = ((uint)(2));
			w96.LeftAttach = ((uint)(1));
			w96.RightAttach = ((uint)(2));
			w96.XOptions = ((global::Gtk.AttachOptions)(4));
			w96.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label34 = new global::Gtk.Label();
			this.label34.Name = "label34";
			this.label34.Xalign = 1F;
			this.table6.Add(this.label34);
			global::Gtk.Table.TableChild w97 = ((global::Gtk.Table.TableChild)(this.table6[this.label34]));
			w97.LeftAttach = ((uint)(1));
			w97.RightAttach = ((uint)(2));
			w97.XOptions = ((global::Gtk.AttachOptions)(4));
			w97.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.lights13 = new global::Gtk.Label();
			this.lights13.Name = "lights13";
			this.lights13.Xalign = 0F;
			this.lights13.LabelProp = global::Mono.Unix.Catalog.GetString("Свет");
			this.table6.Add(this.lights13);
			global::Gtk.Table.TableChild w98 = ((global::Gtk.Table.TableChild)(this.table6[this.lights13]));
			w98.TopAttach = ((uint)(4));
			w98.BottomAttach = ((uint)(5));
			w98.XOptions = ((global::Gtk.AttachOptions)(4));
			w98.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.lightsbutton4 = new global::Gtk.CheckButton();
			this.lightsbutton4.Sensitive = false;
			this.lightsbutton4.CanFocus = true;
			this.lightsbutton4.Name = "lightsbutton4";
			this.lightsbutton4.Label = "";
			this.lightsbutton4.DrawIndicator = true;
			this.lightsbutton4.UseUnderline = true;
			this.table6.Add(this.lightsbutton4);
			global::Gtk.Table.TableChild w99 = ((global::Gtk.Table.TableChild)(this.table6[this.lightsbutton4]));
			w99.TopAttach = ((uint)(4));
			w99.BottomAttach = ((uint)(5));
			w99.LeftAttach = ((uint)(1));
			w99.RightAttach = ((uint)(2));
			w99.XOptions = ((global::Gtk.AttachOptions)(4));
			w99.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.speedlabel4 = new global::Gtk.Label();
			this.speedlabel4.Name = "speedlabel4";
			this.speedlabel4.Xalign = 1F;
			this.table6.Add(this.speedlabel4);
			global::Gtk.Table.TableChild w100 = ((global::Gtk.Table.TableChild)(this.table6[this.speedlabel4]));
			w100.TopAttach = ((uint)(2));
			w100.BottomAttach = ((uint)(3));
			w100.LeftAttach = ((uint)(1));
			w100.RightAttach = ((uint)(2));
			w100.XOptions = ((global::Gtk.AttachOptions)(4));
			w100.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table1.Add(this.table6);
			global::Gtk.Table.TableChild w101 = ((global::Gtk.Table.TableChild)(this.table1[this.table6]));
			w101.TopAttach = ((uint)(7));
			w101.BottomAttach = ((uint)(8));
			w101.LeftAttach = ((uint)(3));
			w101.RightAttach = ((uint)(4));
			w101.XOptions = ((global::Gtk.AttachOptions)(4));
			w101.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.table7 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
			this.table7.Name = "table7";
			this.table7.RowSpacing = ((uint)(6));
			this.table7.ColumnSpacing = ((uint)(6));
			// Container child table7.Gtk.Table+TableChild
			this.distlabel5 = new global::Gtk.Label();
			this.distlabel5.Name = "distlabel5";
			this.distlabel5.Xalign = 1F;
			this.table7.Add(this.distlabel5);
			global::Gtk.Table.TableChild w102 = ((global::Gtk.Table.TableChild)(this.table7[this.distlabel5]));
			w102.TopAttach = ((uint)(3));
			w102.BottomAttach = ((uint)(4));
			w102.LeftAttach = ((uint)(1));
			w102.RightAttach = ((uint)(2));
			w102.XOptions = ((global::Gtk.AttachOptions)(4));
			w102.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.info_but5 = new global::Gtk.ToggleButton();
			this.info_but5.Sensitive = false;
			this.info_but5.CanFocus = true;
			this.info_but5.Name = "info_but5";
			this.info_but5.UseUnderline = true;
			this.info_but5.Label = global::Mono.Unix.Catalog.GetString("Свойства");
			this.table7.Add(this.info_but5);
			global::Gtk.Table.TableChild w103 = ((global::Gtk.Table.TableChild)(this.table7[this.info_but5]));
			w103.TopAttach = ((uint)(5));
			w103.BottomAttach = ((uint)(6));
			w103.XOptions = ((global::Gtk.AttachOptions)(4));
			w103.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.Xalign = 0F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Тип транспорта:");
			this.table7.Add(this.label22);
			global::Gtk.Table.TableChild w104 = ((global::Gtk.Table.TableChild)(this.table7[this.label22]));
			w104.XOptions = ((global::Gtk.AttachOptions)(4));
			w104.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.Xalign = 0F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Тип топлива:");
			this.table7.Add(this.label23);
			global::Gtk.Table.TableChild w105 = ((global::Gtk.Table.TableChild)(this.table7[this.label23]));
			w105.TopAttach = ((uint)(1));
			w105.BottomAttach = ((uint)(2));
			w105.XOptions = ((global::Gtk.AttachOptions)(4));
			w105.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label24 = new global::Gtk.Label();
			this.label24.Name = "label24";
			this.label24.Xalign = 0F;
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Скорость (км/ч):");
			this.table7.Add(this.label24);
			global::Gtk.Table.TableChild w106 = ((global::Gtk.Table.TableChild)(this.table7[this.label24]));
			w106.TopAttach = ((uint)(2));
			w106.BottomAttach = ((uint)(3));
			w106.XOptions = ((global::Gtk.AttachOptions)(4));
			w106.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.Xalign = 0F;
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Пройдено (км):");
			this.table7.Add(this.label25);
			global::Gtk.Table.TableChild w107 = ((global::Gtk.Table.TableChild)(this.table7[this.label25]));
			w107.TopAttach = ((uint)(3));
			w107.BottomAttach = ((uint)(4));
			w107.XOptions = ((global::Gtk.AttachOptions)(4));
			w107.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label30 = new global::Gtk.Label();
			this.label30.Name = "label30";
			this.label30.Xalign = 1F;
			this.table7.Add(this.label30);
			global::Gtk.Table.TableChild w108 = ((global::Gtk.Table.TableChild)(this.table7[this.label30]));
			w108.TopAttach = ((uint)(1));
			w108.BottomAttach = ((uint)(2));
			w108.LeftAttach = ((uint)(1));
			w108.RightAttach = ((uint)(2));
			w108.XOptions = ((global::Gtk.AttachOptions)(4));
			w108.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label35 = new global::Gtk.Label();
			this.label35.Name = "label35";
			this.label35.Xalign = 1F;
			this.table7.Add(this.label35);
			global::Gtk.Table.TableChild w109 = ((global::Gtk.Table.TableChild)(this.table7[this.label35]));
			w109.LeftAttach = ((uint)(1));
			w109.RightAttach = ((uint)(2));
			w109.XOptions = ((global::Gtk.AttachOptions)(4));
			w109.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.lights12 = new global::Gtk.Label();
			this.lights12.Name = "lights12";
			this.lights12.Xalign = 0F;
			this.lights12.LabelProp = global::Mono.Unix.Catalog.GetString("Свет");
			this.table7.Add(this.lights12);
			global::Gtk.Table.TableChild w110 = ((global::Gtk.Table.TableChild)(this.table7[this.lights12]));
			w110.TopAttach = ((uint)(4));
			w110.BottomAttach = ((uint)(5));
			w110.XOptions = ((global::Gtk.AttachOptions)(4));
			w110.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.lightsbutton5 = new global::Gtk.CheckButton();
			this.lightsbutton5.Sensitive = false;
			this.lightsbutton5.CanFocus = true;
			this.lightsbutton5.Name = "lightsbutton5";
			this.lightsbutton5.Label = "";
			this.lightsbutton5.DrawIndicator = true;
			this.lightsbutton5.UseUnderline = true;
			this.table7.Add(this.lightsbutton5);
			global::Gtk.Table.TableChild w111 = ((global::Gtk.Table.TableChild)(this.table7[this.lightsbutton5]));
			w111.TopAttach = ((uint)(4));
			w111.BottomAttach = ((uint)(5));
			w111.LeftAttach = ((uint)(1));
			w111.RightAttach = ((uint)(2));
			w111.XOptions = ((global::Gtk.AttachOptions)(4));
			w111.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.speedlabel5 = new global::Gtk.Label();
			this.speedlabel5.Name = "speedlabel5";
			this.speedlabel5.Xalign = 1F;
			this.table7.Add(this.speedlabel5);
			global::Gtk.Table.TableChild w112 = ((global::Gtk.Table.TableChild)(this.table7[this.speedlabel5]));
			w112.TopAttach = ((uint)(2));
			w112.BottomAttach = ((uint)(3));
			w112.LeftAttach = ((uint)(1));
			w112.RightAttach = ((uint)(2));
			w112.XOptions = ((global::Gtk.AttachOptions)(4));
			w112.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table1.Add(this.table7);
			global::Gtk.Table.TableChild w113 = ((global::Gtk.Table.TableChild)(this.table1[this.table7]));
			w113.TopAttach = ((uint)(9));
			w113.BottomAttach = ((uint)(10));
			w113.LeftAttach = ((uint)(3));
			w113.RightAttach = ((uint)(4));
			w113.XOptions = ((global::Gtk.AttachOptions)(4));
			w113.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.common1 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Common"));
			this.common1.CanFocus = true;
			this.common1.Name = "common1";
			this.common1.DrawIndicator = true;
			this.common1.UseUnderline = true;
			this.common1.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox3.Add(this.common1);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.common1]));
			w114.Position = 0;
			w114.Expand = false;
			w114.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.railway1 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Railway"));
			this.railway1.CanFocus = true;
			this.railway1.Name = "railway1";
			this.railway1.DrawIndicator = true;
			this.railway1.UseUnderline = true;
			this.railway1.Group = this.common1.Group;
			this.vbox3.Add(this.railway1);
			global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.railway1]));
			w115.Position = 1;
			w115.Expand = false;
			w115.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.electrified1 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Electrified"));
			this.electrified1.CanFocus = true;
			this.electrified1.Name = "electrified1";
			this.electrified1.DrawIndicator = true;
			this.electrified1.UseUnderline = true;
			this.electrified1.Group = this.common1.Group;
			this.vbox3.Add(this.electrified1);
			global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.electrified1]));
			w116.Position = 2;
			w116.Expand = false;
			w116.Fill = false;
			this.table1.Add(this.vbox3);
			global::Gtk.Table.TableChild w117 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox3]));
			w117.TopAttach = ((uint)(1));
			w117.BottomAttach = ((uint)(2));
			w117.LeftAttach = ((uint)(1));
			w117.RightAttach = ((uint)(2));
			w117.XOptions = ((global::Gtk.AttachOptions)(4));
			w117.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.common2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Common"));
			this.common2.CanFocus = true;
			this.common2.Name = "common2";
			this.common2.DrawIndicator = true;
			this.common2.UseUnderline = true;
			this.common2.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox4.Add(this.common2);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.common2]));
			w118.Position = 0;
			w118.Expand = false;
			w118.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.railway2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Railway"));
			this.railway2.CanFocus = true;
			this.railway2.Name = "railway2";
			this.railway2.DrawIndicator = true;
			this.railway2.UseUnderline = true;
			this.railway2.Group = this.common2.Group;
			this.vbox4.Add(this.railway2);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.railway2]));
			w119.Position = 1;
			w119.Expand = false;
			w119.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.electrified2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Electrified"));
			this.electrified2.CanFocus = true;
			this.electrified2.Name = "electrified2";
			this.electrified2.DrawIndicator = true;
			this.electrified2.UseUnderline = true;
			this.electrified2.Group = this.common2.Group;
			this.vbox4.Add(this.electrified2);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.electrified2]));
			w120.Position = 2;
			w120.Expand = false;
			w120.Fill = false;
			this.table1.Add(this.vbox4);
			global::Gtk.Table.TableChild w121 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox4]));
			w121.TopAttach = ((uint)(3));
			w121.BottomAttach = ((uint)(4));
			w121.LeftAttach = ((uint)(1));
			w121.RightAttach = ((uint)(2));
			w121.XOptions = ((global::Gtk.AttachOptions)(4));
			w121.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.common3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Common"));
			this.common3.CanFocus = true;
			this.common3.Name = "common3";
			this.common3.DrawIndicator = true;
			this.common3.UseUnderline = true;
			this.common3.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox5.Add(this.common3);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.common3]));
			w122.Position = 0;
			w122.Expand = false;
			w122.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.railway3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Railway"));
			this.railway3.CanFocus = true;
			this.railway3.Name = "railway3";
			this.railway3.DrawIndicator = true;
			this.railway3.UseUnderline = true;
			this.railway3.Group = this.common3.Group;
			this.vbox5.Add(this.railway3);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.railway3]));
			w123.Position = 1;
			w123.Expand = false;
			w123.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.electrified3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Electrified"));
			this.electrified3.CanFocus = true;
			this.electrified3.Name = "electrified3";
			this.electrified3.DrawIndicator = true;
			this.electrified3.UseUnderline = true;
			this.electrified3.Group = this.common3.Group;
			this.vbox5.Add(this.electrified3);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.electrified3]));
			w124.Position = 2;
			w124.Expand = false;
			w124.Fill = false;
			this.table1.Add(this.vbox5);
			global::Gtk.Table.TableChild w125 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox5]));
			w125.TopAttach = ((uint)(5));
			w125.BottomAttach = ((uint)(6));
			w125.LeftAttach = ((uint)(1));
			w125.RightAttach = ((uint)(2));
			w125.XOptions = ((global::Gtk.AttachOptions)(4));
			w125.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.common4 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Common"));
			this.common4.CanFocus = true;
			this.common4.Name = "common4";
			this.common4.DrawIndicator = true;
			this.common4.UseUnderline = true;
			this.common4.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox6.Add(this.common4);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.common4]));
			w126.Position = 0;
			w126.Expand = false;
			w126.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.railway4 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Railway"));
			this.railway4.CanFocus = true;
			this.railway4.Name = "railway4";
			this.railway4.DrawIndicator = true;
			this.railway4.UseUnderline = true;
			this.railway4.Group = this.common4.Group;
			this.vbox6.Add(this.railway4);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.railway4]));
			w127.Position = 1;
			w127.Expand = false;
			w127.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.electrified4 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Electrified"));
			this.electrified4.CanFocus = true;
			this.electrified4.Name = "electrified4";
			this.electrified4.DrawIndicator = true;
			this.electrified4.UseUnderline = true;
			this.electrified4.Group = this.common4.Group;
			this.vbox6.Add(this.electrified4);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.electrified4]));
			w128.Position = 2;
			w128.Expand = false;
			w128.Fill = false;
			this.table1.Add(this.vbox6);
			global::Gtk.Table.TableChild w129 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox6]));
			w129.TopAttach = ((uint)(7));
			w129.BottomAttach = ((uint)(8));
			w129.LeftAttach = ((uint)(1));
			w129.RightAttach = ((uint)(2));
			w129.XOptions = ((global::Gtk.AttachOptions)(4));
			w129.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.common5 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Common"));
			this.common5.CanFocus = true;
			this.common5.Name = "common5";
			this.common5.DrawIndicator = true;
			this.common5.UseUnderline = true;
			this.common5.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox7.Add(this.common5);
			global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.common5]));
			w130.Position = 0;
			w130.Expand = false;
			w130.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.railway5 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Railway"));
			this.railway5.CanFocus = true;
			this.railway5.Name = "railway5";
			this.railway5.DrawIndicator = true;
			this.railway5.UseUnderline = true;
			this.railway5.Group = this.common5.Group;
			this.vbox7.Add(this.railway5);
			global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.railway5]));
			w131.Position = 1;
			w131.Expand = false;
			w131.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.electrified5 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Electrified"));
			this.electrified5.CanFocus = true;
			this.electrified5.Name = "electrified5";
			this.electrified5.DrawIndicator = true;
			this.electrified5.UseUnderline = true;
			this.electrified5.Group = this.common5.Group;
			this.vbox7.Add(this.electrified5);
			global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.electrified5]));
			w132.Position = 2;
			w132.Expand = false;
			w132.Fill = false;
			this.table1.Add(this.vbox7);
			global::Gtk.Table.TableChild w133 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox7]));
			w133.TopAttach = ((uint)(9));
			w133.BottomAttach = ((uint)(10));
			w133.LeftAttach = ((uint)(1));
			w133.RightAttach = ((uint)(2));
			w133.XOptions = ((global::Gtk.AttachOptions)(4));
			w133.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table1);
			global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table1]));
			w134.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table(((uint)(2)), ((uint)(4)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.elTime = new global::Gtk.Label();
			this.elTime.Name = "elTime";
			this.elTime.LabelProp = global::Mono.Unix.Catalog.GetString("Elapsed time:");
			this.table2.Add(this.elTime);
			global::Gtk.Table.TableChild w135 = ((global::Gtk.Table.TableChild)(this.table2[this.elTime]));
			w135.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelNTR = new global::Gtk.Label();
			this.labelNTR.Name = "labelNTR";
			this.table2.Add(this.labelNTR);
			global::Gtk.Table.TableChild w136 = ((global::Gtk.Table.TableChild)(this.table2[this.labelNTR]));
			w136.TopAttach = ((uint)(1));
			w136.BottomAttach = ((uint)(2));
			w136.LeftAttach = ((uint)(3));
			w136.RightAttach = ((uint)(4));
			w136.XOptions = ((global::Gtk.AttachOptions)(4));
			w136.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelTelapsed = new global::Gtk.Label();
			this.labelTelapsed.Name = "labelTelapsed";
			this.table2.Add(this.labelTelapsed);
			global::Gtk.Table.TableChild w137 = ((global::Gtk.Table.TableChild)(this.table2[this.labelTelapsed]));
			w137.TopAttach = ((uint)(1));
			w137.BottomAttach = ((uint)(2));
			w137.XOptions = ((global::Gtk.AttachOptions)(4));
			w137.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelTmove = new global::Gtk.Label();
			this.labelTmove.Name = "labelTmove";
			this.table2.Add(this.labelTmove);
			global::Gtk.Table.TableChild w138 = ((global::Gtk.Table.TableChild)(this.table2[this.labelTmove]));
			w138.TopAttach = ((uint)(1));
			w138.BottomAttach = ((uint)(2));
			w138.LeftAttach = ((uint)(1));
			w138.RightAttach = ((uint)(2));
			w138.XOptions = ((global::Gtk.AttachOptions)(4));
			w138.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelTstop = new global::Gtk.Label();
			this.labelTstop.Name = "labelTstop";
			this.table2.Add(this.labelTstop);
			global::Gtk.Table.TableChild w139 = ((global::Gtk.Table.TableChild)(this.table2[this.labelTstop]));
			w139.TopAttach = ((uint)(1));
			w139.BottomAttach = ((uint)(2));
			w139.LeftAttach = ((uint)(2));
			w139.RightAttach = ((uint)(3));
			w139.XOptions = ((global::Gtk.AttachOptions)(4));
			w139.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.numTransport = new global::Gtk.Label();
			this.numTransport.Name = "numTransport";
			this.numTransport.LabelProp = global::Mono.Unix.Catalog.GetString("Number of transport:");
			this.table2.Add(this.numTransport);
			global::Gtk.Table.TableChild w140 = ((global::Gtk.Table.TableChild)(this.table2[this.numTransport]));
			w140.LeftAttach = ((uint)(3));
			w140.RightAttach = ((uint)(4));
			w140.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sumMoveTime = new global::Gtk.Label();
			this.sumMoveTime.Name = "sumMoveTime";
			this.sumMoveTime.LabelProp = global::Mono.Unix.Catalog.GetString("Total moving time:");
			this.table2.Add(this.sumMoveTime);
			global::Gtk.Table.TableChild w141 = ((global::Gtk.Table.TableChild)(this.table2[this.sumMoveTime]));
			w141.LeftAttach = ((uint)(1));
			w141.RightAttach = ((uint)(2));
			w141.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sumStopTime = new global::Gtk.Label();
			this.sumStopTime.Name = "sumStopTime";
			this.sumStopTime.LabelProp = global::Mono.Unix.Catalog.GetString("Total stop time:");
			this.table2.Add(this.sumStopTime);
			global::Gtk.Table.TableChild w142 = ((global::Gtk.Table.TableChild)(this.table2[this.sumStopTime]));
			w142.LeftAttach = ((uint)(2));
			w142.RightAttach = ((uint)(3));
			w142.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table2);
			global::Gtk.Box.BoxChild w143 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table2]));
			w143.Position = 3;
			w143.Expand = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1096;
			this.DefaultHeight = 885;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.start_stop.Clicked += new global::System.EventHandler(this.ToggleProgress);
			this.common5.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.railway5.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.electrified5.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.common4.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.railway4.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.electrified4.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.common3.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.railway3.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.electrified3.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.common2.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.railway2.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.electrified2.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.common1.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.railway1.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.electrified1.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.lightsbutton5.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.info_but5.Clicked += new global::System.EventHandler(this.OnInfoBut5Clicked);
			this.lightsbutton4.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.info_but4.Clicked += new global::System.EventHandler(this.OnInfoBut4Clicked);
			this.lightsbutton3.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.info_but3.Clicked += new global::System.EventHandler(this.OnInfoBut3Clicked);
			this.lightsbutton2.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.info_but2.Clicked += new global::System.EventHandler(this.OnInfoBut2Clicked);
			this.lightsbutton1.Clicked += new global::System.EventHandler(this.StripTypeToggled);
			this.info_but1.Clicked += new global::System.EventHandler(this.OnInfoBut1Clicked);
			this.drawingarea5.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawingarea5ExposeEvent);
			this.drawingarea4.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawingarea4ExposeEvent);
			this.drawingarea3.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawingarea3ExposeEvent);
			this.drawingarea2.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawingarea2ExposeEvent);
			this.drawingarea1.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawingarea1ExposeEvent);
			this.button5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
			this.button4.Clicked += new global::System.EventHandler(this.OnButton4Clicked);
			this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
			this.button2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
			this.button1.Clicked += new global::System.EventHandler(this.TransportInfo1_clicked);
		}
	}
}
