
// This file has been generated by the GUI designer. Do not modify.
namespace Road111
{
	public partial class ErrorWindow
	{
		private global::Gtk.Table table1;

		private global::Gtk.Button error_but;

		private global::Gtk.Label error_label;

		private global::Gtk.VSeparator vseparator3;

		private global::Gtk.VSeparator vseparator5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Road111.ErrorWindow
			this.Name = "Road111.ErrorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("ErrorWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Road111.ErrorWindow.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(4)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.error_but = new global::Gtk.Button();
			this.error_but.CanFocus = true;
			this.error_but.Name = "error_but";
			this.error_but.UseUnderline = true;
			this.error_but.Label = global::Mono.Unix.Catalog.GetString("Ok");
			this.table1.Add(this.error_but);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.error_but]));
			w1.TopAttach = ((uint)(3));
			w1.BottomAttach = ((uint)(4));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.error_label = new global::Gtk.Label();
			this.error_label.Name = "error_label";
			this.error_label.LabelProp = global::Mono.Unix.Catalog.GetString("Невозможно создать данный объект т.к. необходимый тип топлива отсутствует в списк" +
					"е");
			this.table1.Add(this.error_label);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.error_label]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vseparator3 = new global::Gtk.VSeparator();
			this.vseparator3.Name = "vseparator3";
			this.table1.Add(this.vseparator3);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.vseparator3]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vseparator5 = new global::Gtk.VSeparator();
			this.vseparator5.Name = "vseparator5";
			this.table1.Add(this.vseparator5);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.vseparator5]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 589;
			this.DefaultHeight = 404;
			this.vseparator5.Hide();
			this.Show();
		}
	}
}
